import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import B2BState from "./Context/b2bState";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Oll - B2B Panel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <B2BState>
        <body className={inter.className}>{children}</body>
      </B2BState>
    </html>
  );
}
